#!/usr/bin/env python3
"""Render reviewed missing Chapter 1 records without replacing existing quests."""
import argparse
import json
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def render():
    data = json.loads((HERE / 'guide_records.json').read_text(encoding='utf-8'))
    rows = data['records']
    expected = {*range(24069,24100), *range(17891,17926), *range(19225,19241), *range(23271,23300)}
    assert {r['quest'] for r in rows} == expected and len(rows) == len(expected) == 111
    script = (ROOT / 'npc/custom/chapter1/CH1.c').read_text(encoding='utf-8')
    anchors = {(m[4], m[1], int(m[2]), int(m[3])) for m in re.finditer(
        r'(?m)^([^\s,]+),(\d+),(\d+),\d+\t(?:script(?:\(\w+\))?|duplicate\([^\n]+?\))\t([^\t]+)\t', script)}
    output = ['-- Generated by client-patch/chapter1_quests/generate.py; GPL-3.0-or-later.',
              '-- Reviewed quest-specific records; existing client customizations win.',
              'local function quest(id, title, summary, description)',
              '    if QuestInfoList[id] ~= nil then return end',
              '    QuestInfoList[id] = {Title=title, IconName="ico_nq.bmp", Summary=summary, Description=description}',
              'end', '']
    for row in rows:
        assert (row['npc'],row['map'],row['x'],row['y']) in anchors
        text = list(row['description'])
        label = row['npc'].split('#')[0]
        text.append(f"<NAVI>[{label}]<INFO>{row['map']},{row['x']},{row['y']},0,101,0</INFO></NAVI>")
        values = [str(row['quest']), json.dumps(row['title'],ensure_ascii=False),
                  json.dumps(row['summary'],ensure_ascii=False),
                  '{'+', '.join(json.dumps(t,ensure_ascii=False) for t in text)+'}']
        output.append('quest('+', '.join(values)+')')
    return '\n'.join(output)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__); parser.add_argument('--check', action='store_true')
    args = parser.parse_args(); target = HERE / 'SystemEN/Chapter1GuideRecords.lua'; content = render()
    if args.check: assert target.read_text(encoding='utf-8') == content
    else: target.write_text(content, encoding='utf-8', newline='\n')
    print('CHAPTER1_CLIENT_RECORDS_OK 111 generated records')
