"""Generate missing Rune reward metadata from server definitions; never install."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

PACKAGE = Path(__file__).resolve().parent
ROOT = PACKAGE.parents[1]
sys.path.insert(0, str(ROOT / 'tools/ci'))
from audit_enchant_upgrades import renewal_records

IDS = [105616, 105617, *range(105619, 105649)]

def generate():
    items = {r['Id']: r for r in renewal_records(ROOT, 'db/item_db.yml')}
    rows = []
    for iid in IDS:
        row = items[iid]
        assert row['Type'] == 'Usable' and row['Flags']['Container']
        assert re.fullmatch(r'\s*getgroupitem\(IG_[A-Z0-9_]+\);\s*', row['Script'])
        lines = [
            'Open to receive a reward from this container.',
            '_______________________',
            '^0000CCType:^000000 Container',
            '^0000CCWeight:^000000 ' + format(row.get('Weight', 0) / 10, 'g'),
        ]
        rows.append({'id': iid, 'name': row['Name'], 'resource_source': 616 if iid < 105619 else 617,
                     'description': lines})
    text = '-- Generated by rune_reward_metadata/build.py. Existing album/box artwork is reused.\n'
    text += 'local records = {\n'
    for row in rows:
        text += '    {%d, %s, %d, {%s}},\n' % (row['id'], json.dumps(row['name']), row['resource_source'],
                    ', '.join(json.dumps(s) for s in row['description']))
    text += '''}
for _, row in ipairs(records) do
    assert(tbl[row[1]] == nil, "Rune reward metadata would overwrite " .. row[1])
    local artwork = assert(tbl[row[3]], "Missing container artwork source")
    assert(artwork.identifiedResourceName and artwork.unidentifiedResourceName)
    tbl[row[1]] = {
        unidentifiedDisplayName = row[2], identifiedDisplayName = row[2],
        unidentifiedResourceName = artwork.unidentifiedResourceName,
        identifiedResourceName = artwork.identifiedResourceName,
        unidentifiedDescriptionName = row[4], identifiedDescriptionName = row[4],
        slotCount = 0, ClassNum = 0, costume = false
    }
end
'''
    return text, rows

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    text, rows = generate()
    target = PACKAGE / 'SystemEN/itemInfo_RuneRewards.lua'
    if args.write:
        target.write_text(text, encoding='ascii', newline='\n')
    assert target.read_bytes() == text.encode('ascii'), 'Regenerate stale Rune reward metadata'
    print(json.dumps({'records': len(rows), 'sha256': hashlib.sha256(target.read_bytes()).hexdigest()}))

if __name__ == '__main__': main()
