-- Clean-room complete server-effect metadata: 12 crowns + 11 Sky partners.
-- Does not change the active loader. Generic unidentified icon only.
tbl_druidmissingcrowns = {
  [400999] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Time Dimensions Rune Crown (Alitea)",
    identifiedResourceName = "Time_Dimen_R_Crown",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Max HP +120 per 2 refine levels.",
      "Max SP +30 per 2 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Frenzy Fang damage +5% per 4 refine levels.",
      "Quill Spear damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +10%.",
      "Ranged physical damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AARefine +10 or higher:^000000",
      "Physical damage against non-player races +15%.",
      "^0055AARefine +11 or higher:^000000",
      "CRIT +10.",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +3.",
      "^0055AAGrade C or higher:^000000",
      "Max HP +3%.",
      "Max SP +3%.",
      "^0055AAGrade B or higher:^000000",
      "Melee physical damage +10%.",
      "Ranged physical damage +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all sizes +15%.",
      "_______________________",
      "^0055AASet: with Dimensions Nature Axe (ID 620059)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Savage Lunge damage +60%.",
      "^0055AAcrown Grade A; right-hand weapon Grade A:^000000",
      "Savage Lunge damage +1% per combined crown/right-hand weapon",
      "refine level.",
      "Frenzy Fang cooldown -0.2 sec.",
      "_______________________",
      "^0055AASet: with Dimensions Nature Dagger (ID 510193)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Tempest Flap damage +45%.",
      "Ranged physical damage +15%.",
      "^0055AAcrown Grade A; right-hand weapon Grade A:^000000",
      "Quill Spear damage +1% per combined crown/right-hand weapon",
      "refine level.",
      "Quill Spear cooldown -0.2 sec.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 250",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Alitea (trait class)",
    },
    slotCount = 1, ClassNum = 2441, costume = false
  },
  [401171] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Shadow Cross)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "CRIT +2 per 2 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Savage Impact damage +5% per 4 refine levels.",
      "Critical-damage bonus +3% per 3 refine levels.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +10%.",
      "^0055AARefine +11 or higher:^000000",
      "After-cast delay -10%.",
      "^0055AAGrade C or higher:^000000",
      "CRIT +10.",
      "C.RATE +5.",
      "_______________________",
      "^0055AASet: with Sky Slasher Katar (ID 610093)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Savage Impact damage +20%.",
      "Critical-damage bonus +20%.",
      "^0055AAcrown Grade A; Savage Impact learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Savage Impact cooldown -0.2 sec.",
      "Melee physical damage +10%.",
      "Critical-damage bonuses apply at half their rate to critical",
      "skills in Renewal.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Shadow Cross (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401172] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Arch Mage)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "MATK +2% per 3 refine levels.",
      "Dark-element magic damage +2% per 3 refine levels.",
      "Soul Vulcan Strike damage +5% per 4 refine levels.",
      "Mystery Illusion damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Ghost-element magic damage +10%.",
      "Dark-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "^0055AAGrade C or higher:^000000",
      "Ghost-element magic damage +10%.",
      "Neutral-element magic damage +10%.",
      "Dark-element magic damage +10%.",
      "_______________________",
      "^0055AASet: with Sky Deadsoul Staff (ID 550194)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Mystery Illusion damage +40%.",
      "Astral Strike damage +40%.",
      "^0055AAcrown Grade A; Astral Strike learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Soul Vulcan Strike cooldown -0.2 sec.",
      "Astral Strike damage +20%.",
      "Neutral-element magic damage +15%.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Arch Mage (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401173] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Biolo)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "CRIT +2 per 2 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Mayhemic Thorns damage +5% per 4 refine levels.",
      "Critical-damage bonus +3% per 3 refine levels.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "^0055AARefine +7 or higher:^000000",
      "Ranged physical damage +10%.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade C or higher:^000000",
      "Ranged physical damage +15%.",
      "_______________________",
      "^0055AASet: with Sky Thorns Sword (ID 500136)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Mayhemic Thorns damage +20%.",
      "Critical-damage bonus +20%.",
      "^0055AAcrown Grade A; Mayhemic Thorns learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Mayhemic Thorns cooldown -0.2 sec.",
      "Mayhemic Thorns damage +10%.",
      "Critical-damage bonuses apply at half their rate to critical",
      "skills in Renewal.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Biolo (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401174] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Troubadour/Trouvere)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "HIT +5 per 2 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Rose Blossom damage +5% per 4 refine levels.",
      "Ranged physical damage +1% per 3 refine levels.",
      "Non-critical physical damage +3% per 3 refine levels.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "^0055AARefine +7 or higher:^000000",
      "Ranged physical damage +10%.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade C or higher:^000000",
      "Perfect-hit chance +10 percentage points.",
      "_______________________",
      "^0055AASet: with Sky Music Violin (ID 570093)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Rose Blossom damage +20%.",
      "Non-critical physical damage +20%.",
      "^0055AAcrown Grade A; Rose Blossom learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Rose Blossom cooldown -0.15 sec.",
      "Ranged physical damage +10%.",
      "_______________________",
      "^0055AASet: with Sky Music Whip (ID 580093)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Rose Blossom damage +20%.",
      "Non-critical physical damage +20%.",
      "^0055AAcrown Grade A; Rose Blossom learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Rose Blossom cooldown -0.15 sec.",
      "Ranged physical damage +10%.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Troubadour/Trouvere (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401175] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Alitea)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "MATK +2% per 3 refine levels.",
      "Water-element magic damage +2% per 3 refine levels.",
      "Glacial Shard damage +5% per 4 refine levels.",
      "Glacial Nova damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Water-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "^0055AAGrade C or higher:^000000",
      "Glacial Nova damage +10%.",
      "_______________________",
      "^0055AASet: with Sky Glacier Mace (ID 590116)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Glacial Nova damage +45%.",
      "Water-element magic damage +15%.",
      "^0055AAcrown Grade A; Glacial Stomp learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Glacial Monolith cooldown -1 sec.",
      "Using Glacial Monolith: 100% trigger chance to autocast Lv. 5",
      "Glacial Stomp.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Alitea (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401176] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Furious Circlet (Alitea)",
    identifiedResourceName = "Flash_of_Lightning",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +10 per 2 refine levels.",
      "MATK +10 per 2 refine levels.",
      "Alpha Claw damage +4% per 3 refine levels.",
      "Terra Harvest damage +4% per 3 refine levels.",
      "Glacial Shard damage +4% per 3 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Variable cast time -15%.",
      "^0055AARefine +9 or higher:^000000",
      "Water-element magic damage +10%.",
      "Earth-element magic damage +10%.",
      "Melee physical damage +10%.",
      "^0055AARefine +11 or higher:^000000",
      "ATK +5%.",
      "MATK +5%.",
      "Fixed cast time -0.3 sec.",
      "^0055AAGrade D or higher:^000000",
      "POW +5.",
      "SPL +5.",
      "CON +5.",
      "P.ATK +3.",
      "S.MATK +3.",
      "^0055AAGrade C or higher:^000000",
      "Melee physical damage +10%.",
      "Water-element magic damage +10%.",
      "Earth-element magic damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "ATK +5%.",
      "MATK +5%.",
      "Fixed cast time -0.2 sec.",
      "^0055AAGrade A:^000000",
      "P.ATK +5.",
      "S.MATK +5.",
      "Melee physical damage +15%.",
      "All-element magic damage +15%.",
      "_______________________",
      "^0055AASet: with Furious Axe (ID 520052)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Physical damage against non-player races +10%.",
      "_______________________",
      "^0055AASet: with Furious Scepter (ID 590117)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Glacial Shard damage +10%.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 30",
      "Required Level: 235",
      "Card Slots: 1",
      "Weight: 30",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Alitea (trait class)",
    },
    slotCount = 1, ClassNum = 2415, costume = false
  },
  [401216] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Dragon Knight)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "HIT +5 per 2 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Dragonic Breath damage +5% per 4 refine levels.",
      "Ranged physical damage +1% per 3 refine levels.",
      "Max HP +3% per 3 refine levels.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "^0055AARefine +7 or higher:^000000",
      "Ranged physical damage +10%.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade C or higher:^000000",
      "Perfect-hit chance +10 percentage points.",
      "_______________________",
      "^0055AASet: with Sky Dragon Spear (ID 630066)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Dragonic Breath damage +20%.",
      "Max HP +20%.",
      "^0055AAcrown Grade A; Dragonic Aura learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Dragonic Breath cooldown -0.15 sec.",
      "Ranged physical damage +10%.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Dragon Knight (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401217] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Elemental Master)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "MATK +2% per 3 refine levels.",
      "Earth-element magic damage +2% per 3 refine levels.",
      "Diamond Storm damage +5% per 4 refine levels.",
      "Terra Drive damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Water-element magic damage +10%.",
      "Earth-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "^0055AAGrade C or higher:^000000",
      "Terra Drive damage +10%.",
      "_______________________",
      "^0055AASet: with Sky Elemental Book (ID 540125)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Terra Drive damage +45%.",
      "Earth-element magic damage +15%.",
      "^0055AAcrown Grade A; Terra Drive learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Diamond Storm cooldown -0.3 sec.",
      "Psychic Stream cooldown -1 sec.",
      "Using Psychic Stream: 100% trigger chance to autocast Lv. 5",
      "Terra Drive.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Elemental Master (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401218] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Shinkiro/Shiranui)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "MATK +2% per 3 refine levels.",
      "Wind-element magic damage +2% per 3 refine levels.",
      "Thundering Cannon damage +5% per 4 refine levels.",
      "Cold Blooded Cannon damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Wind-element magic damage +10%.",
      "Water-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Variable cast time -10%.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "^0055AAGrade C or higher:^000000",
      "Thundering Cannon damage +10%.",
      "_______________________",
      "^0055AASet: with Sky Frost Huuma (ID 650062)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Thundering Cannon damage +45%.",
      "Wind-element magic damage +15%.",
      "^0055AAcrown Grade A; Cold Blooded Cannon learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Thundering Cannon cooldown -0.2 sec.",
      "Using Thundering Cannon: 100% trigger chance to autocast Lv. 10",
      "Cold Blooded Cannon.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Shinkiro/Shiranui (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401219] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Nightwatch)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "HIT +5 per 2 refine levels.",
      "ATK +2% per 3 refine levels.",
      "The Vigilante at Night damage +5% per 4 refine levels.",
      "Ranged physical damage +1% per 3 refine levels.",
      "Non-critical physical damage +3% per 3 refine levels.",
      "Midnight Fallen damage +5% per 4 refine levels.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "^0055AARefine +7 or higher:^000000",
      "Ranged physical damage +10%.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade C or higher:^000000",
      "Midnight Fallen damage +15%.",
      "_______________________",
      "^0055AASet: with Sky Nightshot Gatling (ID 830047)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Midnight Fallen damage +45%.",
      "Non-critical physical damage +15%.",
      "^0055AAcrown Grade A; Midnight Fallen learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Using The Vigilante at Night: 100% trigger chance to autocast",
      "Lv. 5 Midnight Fallen.",
      "Ranged physical damage +10%.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Nightwatch (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401220] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Soul Ascetic)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "MATK +2% per 3 refine levels.",
      "All-element magic damage +2% per 3 refine levels.",
      "Talisman Of Four Bearing God damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "All-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "^0055AAGrade C or higher:^000000",
      "All-element magic damage +10%.",
      "_______________________",
      "^0055AASet: with Sky Seonang Wand (ID 550197)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Circle Of Directions And Elementals damage +40%.",
      "All-element magic damage +15%.",
      "^0055AAcrown Grade A; Talisman Of Four Bearing God learned at Lv. 5 or^000000",
      "^0055AAhigher; combined crown/right-hand weapon refine at least 24;^000000",
      "^0055AAright-hand weapon Grade A:^000000",
      "Talisman Of Four Bearing God cooldown -0.25 sec.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Soul Ascetic (trait class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [500136] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Thorns Sword",
    identifiedResourceName = "Midgard_T_Sword_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "CRIT +5.",
      "Mayhemic Thorns damage +15%.",
      "ATK +30 per 3 refine levels.",
      "Critical-damage bonus +2% per 3 refine levels.",
      "Mayhemic Thorns damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Critical-damage bonus +25%.",
      "^0055AARefine +9 or higher:^000000",
      "CRIT +10.",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "CRIT +5.",
      "Mayhemic Thorns damage +10%.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Mayhemic Thorns damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Variable cast time -10%.",
      "^0055AAGrade A:^000000",
      "P.ATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Biolo) (ID 401173)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Mayhemic Thorns damage +20%.",
      "Critical-damage bonus +20%.",
      "^0055AAcrown Grade A; Mayhemic Thorns learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Mayhemic Thorns cooldown -0.2 sec.",
      "Mayhemic Thorns damage +10%.",
      "Critical-damage bonuses apply at half their rate to critical",
      "skills in Renewal.",
      "_______________________",
      "Type: 1hSword",
      "Weapon Level: 5",
      "ATK: 220",
      "MATK: 0",
      "Hands: One",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 180",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Biolo (trait class)",
    },
    slotCount = 2, ClassNum = 2, costume = false
  },
  [540125] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Elemental Book",
    identifiedResourceName = "Sky_Elemental_Book",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Variable cast time -5%.",
      "Diamond Storm damage +15%.",
      "MATK +30 per 3 refine levels.",
      "Water-element magic damage +2% per 3 refine levels.",
      "Diamond Storm damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Water-element magic damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Diamond Storm damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "MATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Diamond Storm damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Diamond Storm damage +10%.",
      "^0055AAGrade A:^000000",
      "S.MATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Elemental Master) (ID 401217)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Terra Drive damage +45%.",
      "Earth-element magic damage +15%.",
      "^0055AAcrown Grade A; Terra Drive learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Diamond Storm cooldown -0.3 sec.",
      "Psychic Stream cooldown -1 sec.",
      "Using Psychic Stream: 100% trigger chance to autocast Lv. 5",
      "Terra Drive.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Book",
      "Weapon Level: 5",
      "ATK: 100",
      "MATK: 230",
      "Hands: One",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 180",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Elemental Master (trait class)",
    },
    slotCount = 2, ClassNum = 15, costume = false
  },
  [550194] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Deadsoul Staff",
    identifiedResourceName = "Midgard_Staff_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Weapon is indestructible in battle.",
      "Variable cast time -5%.",
      "Soul Vulcan Strike damage +15%.",
      "MATK +30 per 3 refine levels.",
      "Ghost-element magic damage +2% per 3 refine levels.",
      "Soul Vulcan Strike damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Ghost-element magic damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Soul Vulcan Strike damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "MATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Soul Vulcan Strike damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "After-cast delay -10%.",
      "^0055AAGrade A:^000000",
      "S.MATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Arch Mage) (ID 401172)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Mystery Illusion damage +40%.",
      "Astral Strike damage +40%.",
      "^0055AAcrown Grade A; Astral Strike learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Soul Vulcan Strike cooldown -0.2 sec.",
      "Astral Strike damage +20%.",
      "Neutral-element magic damage +15%.",
      "_______________________",
      "Type: Staff",
      "Weapon Level: 5",
      "ATK: 110",
      "MATK: 230",
      "Hands: One",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 160",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Arch Mage (trait class)",
    },
    slotCount = 2, ClassNum = 10, costume = false
  },
  [550197] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Seonang Wand",
    identifiedResourceName = "Sky_Seonang_Wand",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Weapon is indestructible in battle.",
      "Variable cast time -5%.",
      "Talisman Of Four Bearing God damage +15%.",
      "MATK +30 per 3 refine levels.",
      "All-element magic damage +2% per 3 refine levels.",
      "Talisman Of Four Bearing God damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "All-element magic damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Talisman Of Four Bearing God damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "MATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Talisman Of Four Bearing God damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "MATK +3%.",
      "SPL +5.",
      "^0055AAGrade A:^000000",
      "S.MATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Soul Ascetic) (ID 401220)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Circle Of Directions And Elementals damage +40%.",
      "All-element magic damage +15%.",
      "^0055AAcrown Grade A; Talisman Of Four Bearing God learned at Lv. 5 or^000000",
      "^0055AAhigher; combined crown/right-hand weapon refine at least 24;^000000",
      "^0055AAright-hand weapon Grade A:^000000",
      "Talisman Of Four Bearing God cooldown -0.25 sec.",
      "_______________________",
      "Type: Staff",
      "Weapon Level: 5",
      "ATK: 100",
      "MATK: 230",
      "Hands: One",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 180",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Soul Ascetic (trait class)",
    },
    slotCount = 2, ClassNum = 10, costume = false
  },
  [570093] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Music Violin",
    identifiedResourceName = "Midgard_Viollin_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Perfect-hit chance +5 percentage points.",
      "Rose Blossom damage +15%.",
      "ATK +30 per 3 refine levels.",
      "Non-critical physical damage +2% per 3 refine levels.",
      "Rose Blossom damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Non-critical physical damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Rose Blossom damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Rose Blossom damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Variable cast time -10%.",
      "^0055AAGrade A:^000000",
      "P.ATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Troubadour/Trouvere) (ID 401174)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Rose Blossom damage +20%.",
      "Non-critical physical damage +20%.",
      "^0055AAcrown Grade A; Rose Blossom learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Rose Blossom cooldown -0.15 sec.",
      "Ranged physical damage +10%.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "_______________________",
      "Type: Musical",
      "Weapon Level: 5",
      "ATK: 220",
      "MATK: 0",
      "Hands: One",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 180",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Troubadour/Trouvere (trait class)",
      "Gender: Male",
    },
    slotCount = 2, ClassNum = 13, costume = false
  },
  [580093] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Music Whip",
    identifiedResourceName = "Midgard_Whip_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Perfect-hit chance +5 percentage points.",
      "Rose Blossom damage +15%.",
      "ATK +30 per 3 refine levels.",
      "Non-critical physical damage +2% per 3 refine levels.",
      "Rose Blossom damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Non-critical physical damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Rose Blossom damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Rose Blossom damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Variable cast time -10%.",
      "^0055AAGrade A:^000000",
      "P.ATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Troubadour/Trouvere) (ID 401174)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Rose Blossom damage +20%.",
      "Non-critical physical damage +20%.",
      "^0055AAcrown Grade A; Rose Blossom learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Rose Blossom cooldown -0.15 sec.",
      "Ranged physical damage +10%.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "_______________________",
      "Type: Whip",
      "Weapon Level: 5",
      "ATK: 220",
      "MATK: 0",
      "Hands: One",
      "Normal-attack reach: 2 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 180",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Troubadour/Trouvere (trait class)",
      "Gender: Female",
    },
    slotCount = 2, ClassNum = 14, costume = false
  },
  [590116] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Glacier Mace",
    identifiedResourceName = "Midgard_Mace_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Weapon is indestructible in battle.",
      "Variable cast time -5%.",
      "Glacial Shard damage +15%.",
      "MATK +30 per 3 refine levels.",
      "Water-element magic damage +2% per 3 refine levels.",
      "Glacial Shard damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Water-element magic damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Glacial Shard damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "MATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Glacial Shard damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Glacial Shard damage +10%.",
      "^0055AAGrade A:^000000",
      "S.MATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Alitea) (ID 401175)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Glacial Nova damage +45%.",
      "Water-element magic damage +15%.",
      "^0055AAcrown Grade A; Glacial Stomp learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Glacial Monolith cooldown -1 sec.",
      "Using Glacial Monolith: 100% trigger chance to autocast Lv. 5",
      "Glacial Stomp.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Mace",
      "Weapon Level: 5",
      "ATK: 100",
      "MATK: 230",
      "Hands: One",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 180",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Alitea (trait class)",
    },
    slotCount = 2, ClassNum = 8, costume = false
  },
  [610093] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Slasher Katar",
    identifiedResourceName = "Midgard_Katar_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "CRIT +5.",
      "Savage Impact damage +15%.",
      "ATK +35 per 3 refine levels.",
      "Critical-damage bonus +3% per 3 refine levels.",
      "Savage Impact damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Critical-damage bonus +25%.",
      "^0055AARefine +9 or higher:^000000",
      "CRIT +10.",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "CRIT +5.",
      "Savage Impact damage +10%.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Savage Impact damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "CRIT +5.",
      "C.RATE +7.",
      "^0055AAGrade A:^000000",
      "P.ATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Shadow Cross) (ID 401171)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Savage Impact damage +20%.",
      "Critical-damage bonus +20%.",
      "^0055AAcrown Grade A; Savage Impact learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Savage Impact cooldown -0.2 sec.",
      "Melee physical damage +10%.",
      "Critical-damage bonuses apply at half their rate to critical",
      "skills in Renewal.",
      "_______________________",
      "Type: Katar",
      "Weapon Level: 5",
      "ATK: 310",
      "MATK: 0",
      "Hands: Two",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 200",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Shadow Cross (trait class)",
    },
    slotCount = 2, ClassNum = 16, costume = false
  },
  [630066] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Dragon Spear",
    identifiedResourceName = "Midgard_Lance_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Perfect-hit chance +5 percentage points.",
      "Dragonic Breath damage +15%.",
      "ATK +35 per 3 refine levels.",
      "Ranged physical damage +3% per 3 refine levels.",
      "Dragonic Breath damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Max HP +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Dragonic Breath damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Dragonic Breath damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Variable cast time -10%.",
      "^0055AAGrade A:^000000",
      "P.ATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Dragon Knight) (ID 401216)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Dragonic Breath damage +20%.",
      "Max HP +20%.",
      "^0055AAcrown Grade A; Dragonic Aura learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Dragonic Breath cooldown -0.15 sec.",
      "Ranged physical damage +10%.",
      "_______________________",
      "Type: 2hSpear",
      "Weapon Level: 5",
      "ATK: 370",
      "MATK: 0",
      "Hands: Two",
      "Normal-attack reach: 3 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 400",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Dragon Knight (trait class)",
    },
    slotCount = 2, ClassNum = 5, costume = false
  },
  [650062] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Frost Huuma",
    identifiedResourceName = "Sky_Frost_Humma",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Weapon is indestructible in battle.",
      "Variable cast time -5%.",
      "Cold Blooded Cannon damage +15%.",
      "MATK +35 per 3 refine levels.",
      "Water-element magic damage +3% per 3 refine levels.",
      "Cold Blooded Cannon damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Water-element magic damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "Variable cast time -10%.",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Cold Blooded Cannon damage +15%.",
      "^0055AAGrade D or higher:^000000",
      "MATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "Cold Blooded Cannon damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Cold Blooded Cannon damage +10%.",
      "^0055AAGrade A:^000000",
      "S.MATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Shinkiro/Shiranui) (ID 401218)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Thundering Cannon damage +45%.",
      "Wind-element magic damage +15%.",
      "^0055AAcrown Grade A; Cold Blooded Cannon learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Thundering Cannon cooldown -0.2 sec.",
      "Using Thundering Cannon: 100% trigger chance to autocast Lv. 10",
      "Cold Blooded Cannon.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Huuma",
      "Weapon Level: 5",
      "ATK: 110",
      "MATK: 330",
      "Hands: Two",
      "Normal-attack reach: 1 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 200",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Shinkiro/Shiranui (trait class)",
    },
    slotCount = 2, ClassNum = 22, costume = false
  },
  [830047] = {
    unidentifiedDisplayName = "Unidentified Weapon",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this equipment to view its name." },
    identifiedDisplayName = "Sky Nightshot Gatling",
    identifiedResourceName = "Midgard_Gatling_Gun_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "Perfect-hit chance +5 percentage points.",
      "The Vigilante at Night damage +15%.",
      "ATK +35 per 3 refine levels.",
      "Ranged physical damage +3% per 3 refine levels.",
      "The Vigilante at Night damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Ranged physical damage +25%.",
      "^0055AARefine +9 or higher:^000000",
      "After-cast delay -10%.",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "The Vigilante at Night damage +10%.",
      "P.ATK +5.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "^0055AAGrade C or higher:^000000",
      "The Vigilante at Night damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Perfect-hit chance +10 percentage points.",
      "^0055AAGrade A:^000000",
      "P.ATK +10.",
      "_______________________",
      "^0055AASet: with Sky Rune Crown (Nightwatch) (ID 401219)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Midnight Fallen damage +45%.",
      "Non-critical physical damage +15%.",
      "^0055AAcrown Grade A; Midnight Fallen learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Using The Vigilante at Night: 100% trigger chance to autocast",
      "Lv. 5 Midnight Fallen.",
      "Ranged physical damage +10%.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Gatling",
      "Weapon Level: 5",
      "ATK: 310",
      "MATK: 0",
      "Hands: Two",
      "Normal-attack reach: 9 (project category default)",
      "Required Level: 240",
      "Card Slots: 2",
      "Weight: 180",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Nightwatch (trait class)",
    },
    slotCount = 2, ClassNum = 19, costume = false
  },
}
