// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
BUILDIN_DEF(getpetreward,"ii??"),
BUILDIN_DEF(pnlabidentity,"i"),
BUILDIN_DEF(pnquestremaining,"i"),
BUILDIN_DEF(pnplansearch,"si"),
BUILDIN_DEF(pnplanrecipes,"i"),
BUILDIN_DEF(pnplanrecipe,"si"),
BUILDIN_DEF(pnplansources,"ii"),
BUILDIN_DEF(pnpurchasehistory,"i"),
BUILDIN_DEF(pnpurchasedetail,"s"),

BUILDIN_DEF2(getitem,"getordinaryitem","vi?"),
