-- Generated by rune_reward_metadata/build.py. Existing album/box artwork is reused.
local records = {
    {105616, "Episode 19-21 Card Album", 616, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105617, "Episode 19-21 Boss Card Album", 616, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105619, "Geoborg Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105620, "Geoborg Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105621, "Ice Coast Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105622, "Ice Coast Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105623, "Ice Coast 2-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105624, "Yosker Yorker Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105625, "Yosker Yorker Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105626, "Staff Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105627, "Staff Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105628, "Management Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105629, "Management Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105630, "Management 2-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105631, "Purification Activity Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105632, "Purification Activity Completion Rewards", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105633, "Purification Activity 3-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105634, "Purification Activity 5-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105635, "Civil Support Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105636, "Civil Support Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105637, "Civil Support 2-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105638, "Civil Support 4-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105639, "Group Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105640, "Group Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105641, "Group 3-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105642, "Group 5-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105643, "Frozen Horn Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105644, "Frozen Horn Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105645, "Frozen Horn 3-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105646, "Frozen Horn 5-Set Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105647, "Encroachment Activation Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
    {105648, "Encroachment Completion Reward", 617, {"Open to receive a reward from this container.", "_______________________", "^0000CCType:^000000 Container", "^0000CCWeight:^000000 0"}},
}
for _, row in ipairs(records) do
    assert(tbl[row[1]] == nil, "Rune reward metadata would overwrite " .. row[1])
    local artwork = assert(tbl[row[3]], "Missing container artwork source")
    assert(artwork.identifiedResourceName and artwork.unidentifiedResourceName)
    tbl[row[1]] = {
        unidentifiedDisplayName = row[2], identifiedDisplayName = row[2],
        unidentifiedResourceName = artwork.unidentifiedResourceName,
        identifiedResourceName = artwork.identifiedResourceName,
        unidentifiedDescriptionName = row[4], identifiedDescriptionName = row[4],
        slotCount = 0, ClassNum = 0, costume = false
    }
end
