#!/usr/bin/env python3
"""Generate/check the direct player-skill supply shop against Renewal imports.

Prints source with --emit; does not write files. Crafting recipe ingredients and
skill unlocks are intentionally outside this shop's coverage.
"""
from pathlib import Path
import argparse
import re
import sys
from audit_enchant_upgrades import renewal_records

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tools'))
from inspect_mapcache import load_maps


def catalog():
    items = {}
    for row in renewal_records(ROOT, 'db/item_db.yml'):
        items.setdefault(row['Id'], {}).update(row)
    names = {r['AegisName']: r for r in items.values()}
    player = {s['Name'] for r in renewal_records(ROOT, 'db/skill_tree.yml')
              for s in r.get('Tree', []) if s.get('MaxLevel', 1) > 0}
    # Preserve cost entries when an import overrides unrelated skill fields.
    skills = {}
    for row in renewal_records(ROOT, 'db/skill_db.yml'):
        skill = skills.setdefault(row['Id'], {'costs': {}, 'tools': {}})
        if 'Name' in row:
            skill['name'] = row['Name']
        req = row.get('Requires', {})
        # Match SkillDatabase's slot-based overrides (Level sets slot index).
        slot = 0
        for cost in req.get('ItemCost', []):
            if 'Level' in cost:
                slot = cost['Level'] - 1
            skill['costs'][slot] = (cost['Item'], cost.get('Amount', 0))
            slot += 1
        skill['tools'].update(req.get('Equipment', {}))
    materials, equipment = set(), set()
    for skill in skills.values():
        if skill.get('name') in player:
            materials.update(n for n, amount in skill['costs'].values() if amount > 0)
            equipment.update(n for n, enabled in skill['tools'].items() if enabled)
    extra = {'Poison_Bottle', 'Poison_Paralysis', 'Poison_Leech', 'Poison_Oblivion',
             'Poison_Contamination', 'Poison_Numb', 'Poison_Fever', 'Poison_Laughing', 'Poison_Fatigue'}
    extra.update(n for n in names if n.startswith('Runstone_'))
    groups = {
        'Materials': [names[n] for n in materials],
        'Ammo': [r for r in items.values() if r.get('Type') == 'Ammo'],
        'Runes': [names[n] for n in extra - materials],
        'Tools': [names[n] for n in equipment - materials if names[n].get('Type') != 'Ammo'],
    }
    return {k: sorted(v, key=lambda r: r['Id']) for k, v in groups.items()}


def price(row):
    return max(row.get('Buy', 0) or 1000, 2 * row.get('Sell', 0), 1)


def render(groups):
    text = '''// Generated by tools/ci/skill_supplies_test.py --emit.
// Direct skill-use materials, ammunition, runes/poisons and required tools.
// Not a skill unlocker or a complete crafting-recipe ingredient shop.
// Prices: database Buy, fallback 1000z; at least twice explicit Sell.
-\tscript\tSkill Supplies\t-1,{
\tmes "[Skill Supplies]";
\tmes "Supplies for every job's item-based skills.";
\tmes "Skills must still be learned. Equipment, summons and other requirements still apply.";
\tmes "Prices use normal item buy prices; unpriced items start at 1,000 Zeny.";
\tnext;
\tswitch(select("Skill materials:Ammunition:Runes and poisons:Skill tools:Cancel")) {
\tcase 1: close2; callshop "SS_Materials",1; end;
\tcase 2: close2; callshop "SS_Ammo",1; end;
\tcase 3: close2; callshop "SS_Runes",1; end;
\tcase 4: close2; callshop "SS_Tools",1; end;
\tdefault: close;
\t}
}
'''
    for group, rows in groups.items():
        text += f'\n// {group}: {len(rows)} items\n'
        text += '-\tshop\tSS_' + group + '\t-1,' + ','.join(f"{r['Id']}:{price(r)}" for r in rows) + '\n'
    for suffix in ('', '_a', '_b', '_c', '_d'):
        text += f'izlude{suffix},137,150,4\tduplicate(Skill Supplies)\tSkill Supplies#iz{suffix or "0"}\t4_M_01\n'
    text += 'grademk,42,180,4\tduplicate(Skill Supplies)\tSkill Supplies#grade\t4_M_01\n'
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--emit', action='store_true')
    parser.add_argument('--client', type=Path)
    args = parser.parse_args()
    groups = catalog()
    expected = render(groups)
    if args.emit:
        print(expected, end='')
        return
    assert (ROOT/'npc/custom/skill_supplies.txt').read_text() == expected, 'Catalog is stale'
    assert (ROOT/'npc/scripts_custom.conf').read_text().count('npc: npc/custom/skill_supplies.txt') == 1
    locations = re.findall(r'^(\w+),(\d+),(\d+),4\s+duplicate', expected, re.M)
    maps = {}
    for path in ('db/import/map_cache.dat', 'db/re/map_cache.dat', 'db/map_cache.dat'):
        if (ROOT/path).exists():
            for name, value in load_maps(ROOT/path, {n for n, _, _ in locations}).items():
                maps.setdefault(name, value)
    for name, x, y in locations:
        width, height, cells = maps[name]
        assert 0 <= int(x) < width and 0 <= int(y) < height
        assert cells[int(y)*width+int(x)] in (0, 3), (name, x, y)
    if args.client:
        ids = set()
        for path in args.client.rglob('*.lua'):
            ids.update(map(int, re.findall(rb'\[\s*(\d+)\s*\]\s*=', path.read_bytes())))
        missing = [(r['Id'], r['AegisName']) for rows in groups.values() for r in rows if r['Id'] not in ids]
        assert not missing, f'Client item metadata missing: {missing}'
    for group, rows in groups.items():
        assert len({r['Id'] for r in rows}) == len(rows)
        assert all(price(r) > 0 for r in rows)
        print(f'PASS: {group}: {len(rows)} items')
    print('PASS: catalog matches databases; six walkable NPC placements; single script import')


if __name__ == '__main__':
    main()
