"""Place every Office service in one verified, compact walkable hall."""
import json
from pathlib import Path
import struct
import zlib

from build_main_office import cache_records

ROOT = Path(__file__).resolve().parents[1]
ENTRANCE = (50, 35)
GROUPS = {
    'Everyday': [
        ('Directory', 'PN Office Directory', '4_BOARD3'),
        ('Healer', 'Healer', '4_F_KAFRA1'),
        ('Storage', 'PN Office Storage', '4_F_KAFRA2'),
        ('Reset Girl', 'Reset Girl', '124'),
        ('Card Remover', 'Wise Old Woman#eAcustom', '78'),
        ('Player Settings', 'PN Player Settings', '4_F_KAFRA1'),
        ('Preparation', 'PN Preparation Desk', '4_M_01'),
        ('Inventory Tools', 'PN Inventory Desk', '4_F_KAFRA2'),
        ('Tool Dealer', 'PN Tool Shop', '4_M_01'),
        ('Cafe', 'PN Cafe Shop', '4_F_01'),
    ],
    'Jobs and Pets': [
        ('Job Master', 'Job Master', '123'),
        ('Druid Mentor', 'Druid Mentor', '4_M_SAGE_C'),
        ('Platinum Skills', 'PN Platinum Skills', '94'),
        ('Rental Service', 'Universal Rental NPC', '726'),
        ('Skill Supplies', 'Skill Supplies', '4_M_01'),
        ('Pet Food', 'Pet Enthusiast', '96'),
        ('Pet Care', '#PetGroomer', '96'),
        ('Pet Recovery', 'PN Pet Recovery', '4_F_KAFRA2'),
    ],
    'Adventures': [
        ('My Adventure', 'PN Adventure Desk', '4_BOARD3'),
        ('Progression Guide', 'PN Progression Guide', '4_M_SAGE_C'),
        ('Travel Desk', 'Warper', '4_F_KAFRA3'),
        ('Temporal Tina', 'Temporal Tina#episode', '4_F_KAFRA6'),
        ('Instance Desk', 'PN Instance Desk', '4_BOARD3'),
        ('Party Board', 'PN Party Desk', '4_BOARD3'),
        ('Boss Rewards', 'PN Reward Desk', '4_BOARD3'),
    ],
    'Equipment': [
        ('Damage Lab', 'PN Services', '4_M_01'),
        ('Rune Tablet', 'PN Rune Stone', '4_ENERGY_BLUE'),
        ('Repair', 'PN Office Repair', '86'),
        ('Equipment Enchants', 'Equipment Enchanter#grademk', '4_M_REPAIR'),
        ('Shadow Enchants', 'Shadow Gear Enchanter#grademk', '4_M_REPAIR'),
        ('Master Refiner', 'Master Refiner#grademk', '4_M_DWARF'),
        ('Ore Dealer', 'Ore and Material Dealer#grademk', '4_F_01'),
        ('Rune Crowns', 'Frontier Rune Crown Enchanter#grademk', '4_M_REPAIR'),
        ('Varmundt Runes', 'Varmundt Rune Enchanter#grademk', '4_M_BARMUND'),
        ('Constellation', 'Constellation Enchanter#grademk', '4_M_ALCHE_A'),
        ('Build Notes', 'PN Build Notes', '4_BOARD3'),
        ('Grade Enhancer', 'Sratos#sratos', '4_JP_GARM_H'),
        ('Shadow Supplies', 'Rayja#EnchantRepair', '4_F_01'),
    ],
    'Fashion': [
        ('Stylist', 'Stylist#custom_stylist', '122'),
        ('Gold Points', 'Gold Point Manager#FP', '4_M_MAYOR'),
        ('Fashion Designer', 'Fashion Designer#FP', '4_CAT_SAILOR5'),
        ('Fashion Recycler', 'Gregio Grumani#FP', '4_M_RUSMAN1'),
        ('Fashion Boxes', 'Fashion Box Shop#FP', '4_F_KAFRA1'),
        ('Fashion Catalogue', 'Fashion Catalogue#FP', '4_BOARD3'),
        ('Fashion Enchants', 'Complete Fashion Enchanter#FP', '4_WHITETIGER'),
        ('Copy Teacher', 'PN Copy Teacher', '4_M_01'),
        ('Sword Clan', 'Raffam Oranpere', '10058'),
        ('Arc Wand Clan', 'Devon Aire', '10059'),
        ('Golden Mace Clan', 'Berman Aire', '10060'),
        ('Crossbow Clan', 'Shaam Rumi', '10027'),
    ],
}


def desired(group, index):
    if group == 'Everyday':
        return 30 + index % 5 * 9, 30 + index // 5 * 7
    if group == 'Jobs and Pets':
        return 29 + index % 2 * 6, 44 + index // 2 * 7
    if group == 'Adventures':
        return 43 + index % 3 * 7, 44 + index // 3 * 7
    if group == 'Equipment':
        return 62 + index % 3 * 5, 44 + index // 3 * 6
    return 37 + index % 6 * 6, 68 + index // 6 * 4


def generate():
    # Import here so the existing public flood-fill helper remains reusable.
    from generate_main_office_layout import component
    records = {}
    for rel in ('db/import/map_cache.dat', 'db/re/map_cache.dat', 'db/map_cache.dat'):
        if (ROOT / rel).exists():
            for name, raw in cache_records(ROOT / rel).items():
                records.setdefault(name, raw)
    raw = records['guild_vs1']
    w, h = struct.unpack_from('<hh', raw, 12)
    cells = zlib.decompress(raw[20:])
    reachable = component(w, h, cells, ENTRANCE)
    occupied, rows = set(), []
    lines = ['// Generated by tools/generate_main_office_layout.py.']
    for group, desks in GROUPS.items():
        lines.append('// ' + group)
        for index, (name, source, sprite) in enumerate(desks):
            tx, ty = desired(group, index)
            choices = sorted((p for p in reachable if 26 <= p[0] <= 74 and 27 <= p[1] <= 74),
                             key=lambda p: (abs(p[0]-tx)+abs(p[1]-ty), p))
            for x, y in choices:
                if max(abs(x-ENTRANCE[0]), abs(y-ENTRANCE[1])) < 3:
                    continue
                if any(max(abs(x-a), abs(y-b)) < 3 for a, b in occupied):
                    continue
                after = component(w, h, cells, ENTRANCE, occupied | {(x, y)})
                approach = next((p for p in ((x,y-1),(x-1,y),(x+1,y),(x,y+1)) if p in after), None)
                if approach and all(tuple(r['approach']) in after for r in rows):
                    break
            else:
                raise ValueError('No reachable compact placement for ' + name)
            assert abs(x-tx)+abs(y-ty) <= 12, (name, x, y)
            occupied.add((x, y))
            unique = name + '#O'
            assert len(unique) < 24
            lines.append(f'pn_office,{x},{y},4\tduplicate({source})\t{unique}\t{sprite}')
            rows.append(dict(name=name, group=group, map='pn_office', npc=[x,y],
                             approach=list(approach), source=source, unique_name=unique))
    lines += ['', 'function\tscript\tPN_OfficeIndex\t{']
    values = [('@PNDeskNames$', ['['+r['group']+'] '+r['name'] for r in rows]),
              ('@PNDeskMaps$', ['pn_office']*len(rows)),
              ('@PNDeskX', [r['approach'][0] for r in rows]),
              ('@PNDeskY', [r['approach'][1] for r in rows]),
              ('@PNDeskGroup$', [r['group'] for r in rows])]
    for var, items in values:
        lines.append('\tsetarray '+var+','+','.join(json.dumps(v) for v in items)+';')
    lines += ['\treturn;', '}', '']
    for suffix in ('', '_a', '_b', '_c', '_d'):
        lines.append(f'izlude{suffix},146,146,4\tduplicate(PN Office Access)\tMain Office#iz{suffix}\t4_M_01')
    lines.append('grademk,20,179,4\tduplicate(PN Office Access)\tMain Office#gr\t4_M_01')
    folder = ROOT / 'npc/custom/main_office'
    target = folder / 'placements.txt'
    prefix = target.read_text().partition('// Generated by tools/generate_main_office_layout.py.')[0]
    target.write_text(prefix+'\n'.join(lines)+'\n')
    layout = dict(version=2, entrances={'pn_office':ENTRANCE}, source='guild_vs1',
                  bounds=[26,27,74,74], groups=list(GROUPS), desks=rows)
    (folder/'layout.json').write_text(json.dumps(layout,indent=2)+'\n')
    print(f'Generated {len(rows)} reachable desks in one compact hall, five groups.')


if __name__ == '__main__':
    generate()
