"""Typed, source-derived inventory outputs for three reviewed dynamic services.

This is deliberately a bounded extractor, not a script interpreter. Unsupported
recipe syntax fails closed. Native VM fixtures remain the execution oracle.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools/ci'))
from audit_enchant_upgrades import renewal_records

CATALOG = 'npc/custom/dynamic_reward_catalog.json'
RUNE = 'npc/custom/rune_tablet/catalog.json'
SERVICES = 'npc/custom/rune_tablet/services.txt'
QUESTS = 'npc/custom/varmundt_biosphere_quests.txt'
DEPTH = 'npc/custom/varmundt_biosphere_depth.txt'


def require(condition, message):
    if not condition:
        raise ValueError(message)


def generate(root=ROOT):
    sources = {}
    def read(path):
        raw = (root / path).read_bytes()
        sources[path] = hashlib.sha256(raw).hexdigest()
        return raw.decode('utf-8-sig')
    rune = json.loads(read(RUNE))
    from generate_rune_tablet_data import generate as rune_script
    runtime=read('npc/custom/rune_tablet/data.txt').replace('\r\n','\n')
    marker='// Generated by tools/generate_rune_tablet_data.py;'
    prefix=runtime.split(marker,1)[0]
    require(all(not line.strip() or line.lstrip().startswith('//') for line in prefix.splitlines()),'Unexpected Rune generated prefix')
    require(marker in runtime and runtime[runtime.index(marker):]==rune_script(rune),
        'Rune generated runtime definitions differ from authoritative catalog')
    service = read(SERVICES)
    quests, depth = read(QUESTS), read(DEPTH)
    rows = []
    def add(family, key, outputs, source, expression, costs=(), repeat='repeatable', condition='', batch=1):
        text = service if source == SERVICES else quests if source == QUESTS else depth
        start, end = 0, len(text)
        if family in ('rune.print', 'rune.shop'):
            start = text.index('PN_RT_Print\t{' if family == 'rune.print' else 'PN_RT_Shop\t{')
            end = text.index('\nfunction', start)
        lines = [text.count('\n',0,m.start())+1 for m in re.finditer(re.escape(expression),text) if start <= m.start() < end]
        require(len(lines) == 1, 'Grant expression drift: ' + expression)
        rows.append(dict(family=family, key=str(key), output_kind='inventory_item',
            outputs=[dict(item_id=i, minimum=lo, maximum=hi, chance_per_100000=chance) for i,lo,hi,chance in outputs],
            costs=[dict(item_id=i, amount=n) for i,n in costs], batch_maximum=batch,
            repeat=repeat, condition=condition, source=source, line=lines[0], expression=expression))
    exact = lambda pairs: [(i,n,n,100000) for i,n in pairs]
    for tablet in rune['sets']:
        for tier, outputs in tablet['rewards'].items():
            if outputs:
                add('rune.milestone', f"{tablet['id']}:{tier}", exact(outputs), SERVICES,
                    'getitem @RT_RewardIds[.@i],@RT_RewardAmounts[.@i];',
                    repeat='once_per_account_and_tablet_tier', condition='paid activation and required registered pieces')
    for recipe in rune['prints']:
        add('rune.print', recipe['id'], exact([(recipe['output'],1)]), SERVICES, 'getitem .@out,1;', recipe['cost'])
    for recipe in rune['shop']:
        add('rune.shop', recipe['id'], exact([(recipe['id'],1)]), SERVICES, 'getitem .@out,1;', recipe['cost'])
    for material, batches in rune['decomposition'].items():
        for batch, outputs in batches.items():
            add('rune.decomposition', material+':'+batch, outputs, SERVICES,
                'getitem @RT_DecompIds[.@i],.@quantity;', [(int(material),int(batch))], condition='independent random draw per output')
    for card in rune['seals']:
        add('rune.seal',card,exact([(1001594,1)]),SERVICES,'getitem 1001594,1;',[(card,1)],
            condition='one card from Rune catalog seal whitelist')
    def array(text, name, index=0):
        hits = re.findall(r'setarray \.@'+name+r'\['+str(index)+r'\],([\d,]+);', text)
        require(len(hits)==1, 'Array syntax drift: '+name)
        return [int(v) for v in hits[0].split(',')]
    def expect(text, expression):
        require(expression in text, 'Recipe formula drift: '+expression)
    omega = quests[quests.index('Omega#'):quests.index('// Only Omega')]
    for token in ('.@output = .@rune[.@element];', '.@output = .@essence[.@element];', '.@need = 10;', '.@need = 5;', 'F_BiosphereMaterialCommit",.@amount,.@output,20000,0,1,.@input,.@need', 'F_BiosphereMaterialCommit",.@amount,.@water[.@water_type],20000,0,5'):
        expect(omega,token)
    fragments,runes,essences = [array(omega,n) for n in ('fragment','rune','essence')]
    require(len(fragments)==len(runes)==len(essences)==7,'Omega element count drift')
    def material(key, output, costs, price, condition):
        add('biosphere.material',key,exact([(output,1)]),QUESTS,'getitem .@result,.@amount;',costs,condition=condition,batch=30000)
        rows[-1]['zeny_per_batch']=price
    for i,(fragment,rune_id,essence) in enumerate(zip(fragments,runes,essences)):
        material('omega:'+str(i)+':1',rune_id,[(fragment,10)],20000,'ba_in01; BaseLevel >= 240')
        material('omega:'+str(i)+':2',essence,[(rune_id,5)],20000,'ba_in01; BaseLevel >= 240')
    common,special,water = [array(omega,n) for n in ('common_essence','special_essence','water')]
    expect(omega,'F_BiosphereMaterialCommit",.@amount,.@water[.@water_type],20000,0,5,.@common_essence[0],5,.@common_essence[1],5,.@common_essence[2],5,.@common_essence[3],5,.@special_essence[.@water_type],5')
    require(len(common)==4 and len(special)==len(water)==3,'Omega water count drift')
    for i,(essence,output) in enumerate(zip(special,water)):
        material('water:'+str(i),output,[(v,5) for v in common+[essence]],20000,'ba_in01; BaseLevel >= 240')
    ellie = depth[depth.index('Ellie#bio_d1_fusion'):depth.index('// Armor purchase')]
    expect(ellie,'.@input = 1001290 + .@i + ((.@stage - 1) * 8);')
    expect(ellie,'.@output = .@input + 8;')
    needs,prices = array(ellie,'need',1),array(ellie,'cost',1)
    require(len(needs)==len(prices)==3,'Ellie stage count drift')
    for element in range(8):
        for stage,(need,price) in enumerate(zip(needs,prices)):
            iid=1001290+element+stage*8
            material(f'ellie:{element}:{stage+1}',iid+8,[(iid,need)],price,'ba_in01; BaseLevel >= 250; ep17_2_main >= 33')
    abyss=depth.split('L_Convert:\n',1)[1]
    matches=re.findall(r'case (\d+):\s*setarray \.@mat\[0\],([\d,]+);\s*setarray \.@need\[0\],([\d,]+);\s*\.@matcount = (\d+); \.@result = (\d+); \.@cost = (\d+);\s*break;',abyss)
    require(len(matches)==5,'Abyss recipe syntax/count drift')
    for key,mats,needs,n,output,price in matches:
        mats,needs=[int(v) for v in mats.split(',')],[int(v) for v in needs.split(',')]
        require(len(mats)==len(needs)==int(n),'Abyss cost vector mismatch')
        add('abyss.conversion',key,exact([(int(output),1)]),DEPTH,'getitem .@result,.@amount;',list(zip(mats,needs)),
            condition='ba_chess; BaseLevel >= 250; ep17_2_main >= 33; Depth1 reputation >= 2000',batch=30000)
        rows[-1]['zeny_per_batch']=int(price)
    return dict(schema=1,source_sha256=sources,recipes=rows,
        boundary='Bounded recipe catalog; native execution and effective client assets require separate verification. Not a general economy-cycle or gameplay-reachability proof.')


def validate(catalog, root=ROOT, metadata=None, triage=None):
    require(catalog==generate(root),'Declared outputs or source binding differ from authoritative recipes')
    items={}
    def overlay(target, row):
        for key,value in row.items():
            if isinstance(value,dict) and isinstance(target.get(key),dict): overlay(target[key],value)
            else: target[key]=value
    for row in renewal_records(root,'db/item_db.yml'):
        overlay(items.setdefault(row['Id'],{}),row)
    outputs={o['item_id'] for r in catalog['recipes'] for o in r['outputs']}
    for iid in outputs:
        require(iid in items and items[iid].get('AegisName'),'Missing effective server definition: '+str(iid))
    result=dict(recipes=len(catalog['recipes']),output_ids=len(outputs),server='passed',client='not_checked')
    if metadata is not None:
        raw=metadata.read_bytes()
        text=raw.decode('utf-16') if raw.startswith(b'\xff\xfe') else raw.decode('utf-8-sig')
        ids={int(line.split('\t')[0]) for line in text.splitlines() if line.split('\t')[0].isdigit()}
        require(not outputs-ids,'Missing client metadata: '+str(sorted(outputs-ids)))
        require(triage is not None,'Client resource triage is required with metadata')
        audit=json.loads(triage.read_text())
        refs=audit.get('catalog_missing_references',audit.get('lua',{}).get('missing_archive_icons'))
        require(isinstance(refs,list),'Unknown client resource triage schema')
        missing=[r for r in refs if r['item_id'] in outputs]
        require(not missing,'Missing client resources: '+str(missing))
        result.update(client='passed',metadata_sha256=hashlib.sha256(raw).hexdigest(),triage_sha256=hashlib.sha256(triage.read_bytes()).hexdigest())
    return result


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true')
    parser.add_argument('--metadata',type=Path)
    parser.add_argument('--triage',type=Path)
    parser.add_argument('--report',type=Path)
    args=parser.parse_args()
    if args.write: (ROOT/CATALOG).write_text(json.dumps(generate(),indent=2)+'\n')
    try:
        result=validate(json.loads((ROOT/CATALOG).read_text()),metadata=args.metadata,triage=args.triage)
    except ValueError as error:
        result=dict(status='failed',error=str(error))
        if args.report: args.report.write_text(json.dumps(result,indent=2)+'\n')
        raise SystemExit(str(error))
    print(json.dumps(result,indent=2))
    if args.report: args.report.write_text(json.dumps(result,indent=2)+'\n')


if __name__=='__main__': main()
