"""Arrange the original Grade Workshop on its existing walkable interior floor."""
from collections import deque
import hashlib
import json
from pathlib import Path
import re

from inspect_mapcache import load_maps

ROOT = Path(__file__).resolve().parents[1]
ARRIVALS = ((13, 172), (34, 184))
SERVICES = (
    ('npc/custom/shadow_repair.txt', 'Rayja#EnchantRepair', (22, 181), 'Shadow books and materials', 'Upgrades'),
    ('npc/custom/grademk_equipment_enchants.txt', 'Equipment Enchanter#grademk', (26, 181), 'Equipment enchants', 'Upgrades'),
    ('npc/re/merchants/enchantgrade.txt', 'Sratos#sratos', (32, 181), 'Grade enhancement', 'Upgrades'),
    ('npc/custom/grademk_services.txt', 'Master Refiner#grademk', (38, 181), 'Refinement', 'Upgrades'),
    ('npc/custom/grademk_services.txt', 'Ore and Material Dealer#grademk', (42, 181), 'Ore and materials', 'Upgrades'),
    ('npc/custom/healer.txt', 'Healer#grademk', (20, 175), 'Healing', 'Support'),
    ('npc/custom/episode_skip_tina.txt', 'Temporal Tina#grademk', (24, 175), 'Episode progress', 'Support'),
    ('npc/custom/skill_supplies.txt', 'Skill Supplies#grade', (40, 175), 'Skill supplies', 'Support'),
    ('npc/custom/rune_tablet/services.txt', 'Rune Stone#PNWorkshop', (44, 175), 'Rune tablet', 'Support'),
    ('npc/custom/quality_services.txt', 'PN Services#grade', (44, 179), 'Damage lab and builds', 'Support'),
)
EXTRA = (('Main Office#gr', (20, 179)), ('Workshop Guide#grademk', (30, 175)))


def geometry(root=ROOT):
    for relative in ('db/import/map_cache.dat', 'db/re/map_cache.dat', 'db/map_cache.dat'):
        path = root / relative
        if path.exists():
            maps = load_maps(path, {'grademk'})
            if 'grademk' in maps:
                return (*maps['grademk'], relative, hashlib.sha256(path.read_bytes()).hexdigest())
    raise AssertionError('Effective Grademk map missing')


def connected(width, height, cells, start, occupied):
    def walk(p):
        x, y = p
        return 0 <= x < width - 1 and 0 <= y < height - 1 and cells[x + y * width] in (0, 2, 3, 4, 6)
    if not walk(start) or start in occupied:
        raise AssertionError(f'Blocked or occupied arrival: {start}')
    seen, pending = {start}, deque([start])
    while pending:
        x, y = pending.popleft()
        for point in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if point not in seen and point not in occupied and walk(point):
                seen.add(point)
                pending.append(point)
    return seen


def generate():
    width, height, cells, cache, digest = geometry()
    all_rows = [(identity, position) for _, identity, position, _, _ in SERVICES] + list(EXTRA)
    occupied = {point for _, point in all_rows}
    assert len(occupied) == len(all_rows), 'Duplicated workshop desk'
    seen = connected(width, height, cells, ARRIVALS[0], occupied)
    for _, point in all_rows:
        x, y = point
        assert cells[x + y * width] in (0, 3), ('Non-floor NPC', point)
        assert (x, y - 1) in seen, ('Disconnected approach', point)
    assert ARRIVALS[1] in seen
    for relative, identity, (x, y), _, _ in SERVICES:
        path = ROOT / relative
        source = path.read_text(encoding='utf-8')
        pattern = r'^grademk,\d+,\d+,4(?=\t[^\n]*\t' + re.escape(identity) + r'\t)'
        source, count = re.subn(pattern, f'grademk,{x},{y},4', source, flags=re.M)
        assert count == 1, ('Unresolved placed service', relative, identity, count)
        path.write_text(source, encoding='utf-8', newline='\n')
    rows = [dict(id=identity, npc=list(point), approach=[point[0], point[1]-1], label=label, group=group, file=relative)
            for relative, identity, point, label, group in SERVICES]
    rows += [dict(id=identity, npc=list(point), approach=[point[0], point[1]-1],
                  label='Main Office' if identity.startswith('Main') else 'Workshop Guide', group='Support')
             for identity, point in EXTRA]
    layout = dict(map='grademk', arrivals=[list(p) for p in ARRIVALS], cache=cache,
                  cache_sha256=digest, services=rows)
    (ROOT / 'npc/custom/grade_workshop_layout.json').write_text(json.dumps(layout, indent=2)+'\n')
    script = ['// Generated by tools/generate_grade_workshop_layout.py.',
              '// Clear central aisle; north counters: Shadow books, enchants, grade, refine, materials.',
              '// Existing services retain their costs, eligibility and unique NPC identities.',
              'function\tscript\tPN_GradeWorkshopDirectory\t{',
              '\tmes "[Grade Workshop]";',
              '\tmes "North counters: Shadow books, equipment enchants, grade enhancement, refinement and ore.";',
              '\tmes "South counters: healing, episode progress, rune tablets and skill supplies.";',
              '\tmes "Choose a service to mark the walking route.";', '\tnext;',
              '\t.@choice = select("'+':'.join(r['label'] for r in rows[:-1])+':Cancel");',
              '\tswitch (.@choice) {']
    for index, row in enumerate(rows[:-1], 1):
        x, y = row['approach']
        script.append(f'\tcase {index}: navigateto "grademk",{x},{y}; break;')
    script += ['\tdefault: return;', '\t}', '\treturn;', '}', '',
               'grademk,30,175,4\tscript\tWorkshop Guide#grademk\t4_BOARD3,{',
               '\tcallfunc "PN_GradeWorkshopDirectory";', '\tclose;', '', 'OnInit:',
               '\tsetunittitle(getnpcid(0), "<Workshop Directory>");', '\tend;', '}', '']
    (ROOT / 'npc/custom/grade_workshop_directory.txt').write_text('\n'.join(script))


if __name__ == '__main__':
    generate()
