#!/usr/bin/env python3
"""Render the curated Chapter 1 guide; verify every coordinate against live NPCs."""
import argparse
import json
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
CATALOG=ROOT/'npc/custom/main_office/chapter1_guide.json'
OUTPUT=ROOT/'npc/custom/main_office/chapter1_guide.txt'

def render():
    data=json.loads(CATALOG.read_text(encoding='utf-8'))
    assert data['schema']==1
    source=(ROOT/data['source']).read_text(encoding='utf-8')
    anchors={(m[4],m[1],int(m[2]),int(m[3])) for m in re.finditer(
        r'(?m)^([^\s,]+),(\d+),(\d+),\d+\t(?:script(?:\(\w+\))?|duplicate\([^\n]+?\))\t([^\t]+)\t',source)}
    expected=({*range(18368,18379),*range(24069,24100),*range(17891,17926),
               *range(16912,16952),*range(19225,19241),*range(23271,23300),
               *range(8955,8970),12663,12664,12665,12666}-{18377})
    assert {r['quest'] for r in data['steps']}==expected, 'Complete story/parallel investigation coverage'
    assert len(data['steps'])==len(expected), 'Duplicate quest row'
    lines=['// Generated by tools/generate_chapter1_guide.py from chapter1_guide.json.',
           '// Read-only directions; actual entrances and conversations own progression.',
           'function\tscript\tPN_CH1GuideCatalog\t{',' .@q=getarg(0);']
    for row in data['steps']:
        assert (row['npc'],row['map'],row['x'],row['y']) in anchors, 'Unknown NPC anchor: '+str(row)
        assert re.search(r'\b'+str(row['quest'])+r'\b',source), 'Unknown story state'
        assert all(len(row[k].encode())<240 for k in ('title','objective'))
        args=[row['quest'],row['title'],row['objective'],row['map'],row['x'],row['y']]
        lines.append(' if (.@q=='+str(row['quest'])+') return callfunc("PN_CH1GuideShow",'+','.join(json.dumps(x,ensure_ascii=False) for x in args)+');')
    lines+=[' return 0;','}', '']
    # Umbrella quests resolve their outstanding sub-objectives first.
    normal=[r['quest'] for r in data['steps'] if r['quest'] not in {19225,19230,8959,17912,*range(17913,17916),*range(19231,19238)}]
    lines+=['function\tscript\tPN_CH1Guide\t{',
      ' if (isbegin_quest(18377)==2) { mes "Chapter 1 complete. Reach Base Level 225, then meet Guardian El at ygg_edge 156,179 for Chapter 2."; navigateto "ygg_edge",156,179; return 1; }',
      ' if (isbegin_quest(19230)==1) {',
      '  for (.@q=19231; .@q<=19237; .@q++) if (isbegin_quest(.@q)!=2) return callfunc("PN_CH1GuideCatalog",.@q);',
      '  return callfunc("PN_CH1GuideCatalog",19230);',' }',
      ' if (isbegin_quest(17912)==1 && isbegin_quest(17911)!=1) {',
      '  for (.@q=17913; .@q<=17915; .@q++) if (isbegin_quest(.@q)!=2) return callfunc("PN_CH1GuideCatalog",.@q);',' }',
      ' if (isbegin_quest(8959)==1) {',
      '  for (.@q=8960; .@q<=8962; .@q++) if (isbegin_quest(.@q)!=2) return callfunc("PN_CH1GuideCatalog",.@q);',' }',
      ' setarray .@quests[0],'+','.join(map(str,normal))+';',
      ' for (.@i=0; .@i<getarraysize(.@quests); .@i++) if (isbegin_quest(.@quests[.@i])==1) return callfunc("PN_CH1GuideCatalog",.@quests[.@i]);',
      ' if (isbegin_quest(19225)==1) return callfunc("PN_CH1GuideCatalog",19225);',
      ' return 0;', '}', '']
    return '\n'.join(lines)

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    content=render()
    if args.check:assert OUTPUT.read_text(encoding='utf-8')==content, 'Regenerate Chapter 1 guide'
    else:OUTPUT.write_text(content,encoding='utf-8',newline='\n')
    print('CHAPTER1_GUIDE_CATALOG_OK entries=180')

if __name__=='__main__':main()
