"""Bind literal barter calls to enabled, located NPC declarations.
Prices/materials remain runtime database data. Conditional access stays with
the real NPC. Dynamic callers are deliberately not guessed.
"""
import argparse
from pathlib import Path
import re
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tools/ci'))
from biosphere_callback_closure_audit import Reader,npc_graph
from biosphere_material_callback_audit import lexical_views,body_end

def literal(value):
    # Legacy NPC names can contain non-UTF-8 bytes; retain the loader identity.
    return '"'+''.join(chr(b) if 32<=b<127 and b not in (34,92) else '\\%03o'%b
                       for b in value.encode('utf-8',errors='surrogateescape'))+'"'

def generate():
    reader=Reader(ROOT);graph=npc_graph(reader);routes=set()
    declaration=re.compile(r'(?m)^([\w@]+),\d+,\d+,\d+\s+script\s+([^\t\r\n]+)\t[^\r\n{]*\{')
    for path in graph['scripts']:
        source=reader.text(path);comments,masked=lexical_views(source)
        for match in declaration.finditer(comments):
            start=source.index('{',match.start());end=body_end(masked,start)
            for call in re.finditer(r'\bcallshop\s*(?:\(\s*)?"([^"\r\n]+)"',comments[start:end]):
                routes.add((call[1],match[2].strip()))
    return '// Generated by tools/generate_planner_routes.py; do not edit.\n'+''.join('{'+literal(shop)+','+literal(npc)+'},\n' for shop,npc in sorted(routes))

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=ROOT/'src/custom/planner_routes.inc';content=generate()
    if args.check:
        if path.read_text()!=content:raise SystemExit('Planner routes are stale; regenerate')
    else:path.write_text(content)
    print('PLANNER_ROUTES_OK',content.count('\n')-1)
