#!/usr/bin/env python3
"""Generate spaced office desks and a directory from verified walkable cells."""
from collections import deque
import json
from pathlib import Path
import struct
import zlib
from build_main_office import cache_records, MAPS

ROOT=Path(__file__).resolve().parents[1]
ENTRANCES={'pn_office':(100,40),'pn_train':(50,35),'pn_style':(140,140)}
# Display name, existing script/shop, desired x/y, sprite. Names include a short
# unique suffix in the generated script; existing service rules are reused.
DESKS={
 'pn_office':[
  ('Directory','PN Office Directory',104,42,'4_BOARD3'),
  ('Healer','Healer',92,40,'4_F_KAFRA1'),
  ('Storage','PN Office Storage',108,40,'4_F_KAFRA2'),
  ('Reset Girl','Reset Girl',84,55,'124'),
  ('Card Remover','Wise Old Woman#eAcustom',116,55,'78'),
  ('Job Master','Job Master',46,40,'123'),
  ('Druid Mentor','Druid Mentor',56,40,'4_M_SAGE_C'),
  ('Platinum Skills','PN Platinum Skills',66,40,'94'),
  ('Rental Service','Universal Rental NPC',46,50,'726'),
  ('Skill Supplies','Skill Supplies',60,50,'4_M_01'),
  ('Tool Dealer','PN Tool Shop',140,40,'4_M_01'),
  ('Pet Food','Pet Enthusiast',132,50,'96'),
  ('Pet Care','#PetGroomer',150,50,'96'),
  ('Travel Desk','Warper',92,80,'4_F_KAFRA3'),
  ('Progression Guide','PN Progression Guide',108,80,'4_M_SAGE_C'),
  ('Temporal Tina','Temporal Tina#episode',84,90,'4_F_KAFRA6'),
  ('Instance Desk','PN Instance Desk',116,90,'4_BOARD3'),
  ('PN Services','PN Services',100,110,'4_M_01'),
 ],
 'pn_train':[
  ('Directory','PN Office Directory',56,35,'4_BOARD3'),
  ('Damage Lab','PN Services',50,65,'4_M_01'),
  ('Rune Tablet','PN Rune Stone',50,75,'4_ENERGY_BLUE'),
  ('Healer','Healer',44,35,'4_F_KAFRA1'),
  ('Storage','PN Office Storage',36,40,'4_F_KAFRA2'),
  ('Repair','PN Office Repair',64,40,'86'),
  ('Equipment Enchants','Equipment Enchanter#grademk',36,60,'4_M_REPAIR'),
  ('Shadow Enchants','Shadow Gear Enchanter#grademk',64,60,'4_M_REPAIR'),
  ('Master Refiner','Master Refiner#grademk',32,50,'4_M_DWARF'),
  ('Ore Dealer','Ore and Material Dealer#grademk',68,50,'4_F_01'),
  ('Rune Crowns','Frontier Rune Crown Enchanter#grademk',42,68,'4_M_REPAIR'),
  ('Varmundt Runes','Varmundt Rune Enchanter#grademk',58,68,'4_M_BARMUND'),
  ('Constellation','Constellation Enchanter#grademk',42,55,'4_M_ALCHE_A'),
  ('Build Notes','PN Build Notes',58,55,'4_BOARD3'),
  ('Card Remover','Wise Old Woman#eAcustom',42,45,'78'),
  ('Reset Girl','Reset Girl',58,45,'124'),
 ],
 'pn_style':[
  ('Directory','PN Office Directory',140,145,'4_BOARD3'),
  ('Stylist','Stylist#custom_stylist',128,130,'122'),
  ('Gold Points','Gold Point Manager#FP',136,130,'4_M_MAYOR'),
  ('Fashion Designer','Fashion Designer#FP',144,130,'4_CAT_SAILOR5'),
  ('Fashion Recycler','Gregio Grumani#FP',152,130,'4_M_RUSMAN1'),
  ('Fashion Boxes','Fashion Box Shop#FP',160,130,'4_F_KAFRA1'),
  ('Fashion Catalogue','Fashion Catalogue#FP',128,138,'4_BOARD3'),
  ('Fashion Enchants','Complete Fashion Enchanter#FP',160,138,'4_WHITETIGER'),
  ('Copy Teacher','PN Copy Teacher',128,146,'4_M_01'),
  ('Sword Clan','Raffam Oranpere',136,151,'10058'),
  ('Arc Wand Clan','Devon Aire',144,151,'10059'),
  ('Golden Mace Clan','Berman Aire',152,151,'10060'),
  ('Crossbow Clan','Shaam Rumi',160,146,'10027'),
  ('Cafe','PN Cafe Shop',136,122,'4_F_01'),
  ('Storage','PN Office Storage',144,122,'4_F_KAFRA2'),
  ('Healer','Healer',152,122,'4_F_KAFRA1'),
 ]}

def component(w,h,cells,start,blocked=frozenset()):
    seen={start};queue=deque([start])
    assert cells[start[0]+start[1]*w] in (0,3) and start not in blocked, ('bad entrance',start)
    while queue:
        x,y=queue.popleft()
        for p in [(x-1,y),(x+1,y),(x,y-1),(x,y+1)]:
            a,b=p
            if 0<=a<w and 0<=b<h and p not in seen and p not in blocked and cells[a+b*w] in (0,3):
                seen.add(p);queue.append(p)
    return seen

def generate():
    effective={}
    for rel in ['db/import/map_cache.dat','db/re/map_cache.dat','db/map_cache.dat']:
        if (ROOT/rel).exists():
            for name,raw in cache_records(ROOT/rel).items():effective.setdefault(name,raw)
    rows=[];lines=['// Generated by tools/generate_main_office_layout.py.']
    for floor,desks in DESKS.items():
        raw=effective[MAPS[floor]];w,h=struct.unpack_from('<hh',raw,12);cells=zlib.decompress(raw[20:])
        reachable=component(w,h,cells,ENTRANCES[floor]);occupied=set()
        for i,(display,source,tx,ty,sprite) in enumerate(desks):
            candidates=sorted(reachable,key=lambda p:(abs(p[0]-tx)+abs(p[1]-ty),p))
            for x,y in candidates:
                if max(abs(x-ENTRANCES[floor][0]),abs(y-ENTRANCES[floor][1])) < 3:continue
                if any(max(abs(x-a),abs(y-b))<4 for a,b in occupied):continue
                approaches=[(x,y-1),(x-1,y),(x+1,y),(x,y+1)]
                after=component(w,h,cells,ENTRANCES[floor],occupied|{(x,y)})
                approach=next((p for p in approaches if p in after),None)
                if approach and all(tuple(r['approach']) in after for r in rows if r['map']==floor):break
            else:raise ValueError('No space for '+display)
            assert abs(x-tx)+abs(y-ty)<=18,('Excessive placement adjustment',floor,display,x,y)
            occupied.add((x,y))
            name=display+'#'+{'pn_office':'O','pn_train':'T','pn_style':'F'}[floor]
            assert len(name)<24
            lines.append(f'{floor},{x},{y},4\tduplicate({source})\t{name}\t{sprite}')
            rows.append({'name':display,'map':floor,'npc':[x,y],'approach':list(approach),'source':source,'unique_name':name})
        final=component(w,h,cells,ENTRANCES[floor],occupied)
        assert all(tuple(r['approach']) in final for r in rows if r['map']==floor)
    lines+=['','function\tscript\tPN_OfficeIndex\t{']
    arrays=[('@PNDeskNames$', ['['+{'pn_office':'Lobby','pn_train':'Training','pn_style':'Fashion'}[r['map']]+'] '+r['name'] for r in rows]),
            ('@PNDeskMaps$',[r['map'] for r in rows]),('@PNDeskX',[r['approach'][0] for r in rows]),('@PNDeskY',[r['approach'][1] for r in rows])]
    for var,values in arrays:
        lines.append('\tsetarray '+var+','+','.join(json.dumps(v) for v in values)+';')
    lines+=['\treturn;','}','',
      'prontera,156,185,4\tduplicate(PN Office Access)\tMain Office#prt\t4_M_01',
      'izlude,146,146,4\tduplicate(PN Office Access)\tMain Office#iz\t4_M_01',
      'izlude_a,146,146,4\tduplicate(PN Office Access)\tMain Office#iza\t4_M_01',
      'izlude_b,146,146,4\tduplicate(PN Office Access)\tMain Office#izb\t4_M_01',
      'izlude_c,146,146,4\tduplicate(PN Office Access)\tMain Office#izc\t4_M_01',
      'izlude_d,146,146,4\tduplicate(PN Office Access)\tMain Office#izd\t4_M_01',
      'grademk,50,180,4\tduplicate(PN Office Access)\tMain Office#gr\t4_M_01','']
    folder=ROOT/'npc/custom/main_office'
    (folder/'placements.txt').write_text('\n'.join(lines))
    (folder/'layout.json').write_text(json.dumps({'entrances':ENTRANCES,'desks':rows},indent=2)+'\n')
    print(f'Generated {len(rows)} desks across 3 connected floor areas; all approaches reachable with NPC cells blocked.')

if __name__=='__main__':generate()
