-- Clean-room descriptions derived from effective server item and combo Scripts.
-- Exact twelve-record allowlist; no copied third-party effect descriptions.
-- Existing reference-backed art; generic unidentified icon EpisodClear20.
-- Optional additive import only; no active loader is modified.
tbl_enchanttargets = {
  [401055] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Silver Stardust Crown",
    identifiedResourceName = "Poenetentia_P_Crown",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "POW +5.",
      "CON +5.",
      "Critical-damage bonus +4% per 2 refine levels.",
      "ATK +20 per 2 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +15%.",
      "Ranged physical damage +15%.",
      "^0055AARefine +9 or higher:^000000",
      "C.RATE +5.",
      "ATK +10%.",
      "^0055AARefine +11 or higher:^000000",
      "Critical-damage bonus +25%.",
      "P.ATK +8.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "POW +5.",
      "^0055AAGrade C or higher:^000000",
      "C.RATE +5.",
      "CRIT +15.",
      "^0055AAGrade B or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "Variable cast time -10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against non-player races +3% per 3 refine",
      "levels.",
      "Critical-damage bonus +2% per 3 refine levels.",
      "CRIT +1 per 3 refine levels.",
      "_______________________",
      "^0055AASet: with Executioner's Cloak (ID 480669)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Critical-damage bonus +15%.",
      "P.ATK +5.",
      "^0055AAcrown Grade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Sharpshooter Muffler (ID 480670)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Critical-damage bonus +15%.",
      "P.ATK +5.",
      "^0055AAcrown Grade A:^000000",
      "Physical damage against all target elements +10%.",
      "Critical-damage bonuses apply at half their rate to critical",
      "skills in Renewal.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 60",
      "Required Level: 250",
      "Card Slots: 1",
      "Weight: 40",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: All jobs (subject to required level)",
    },
    slotCount = 1, ClassNum = 2500, costume = false
  },
  [401056] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Scarlet Stardust Crown",
    identifiedResourceName = "Poenetentia_B_Crown",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "POW +5.",
      "CON +5.",
      "ATK +30 per 2 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +15%.",
      "Ranged physical damage +15%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +7.",
      "ATK +12%.",
      "^0055AARefine +11 or higher:^000000",
      "Melee physical damage +25%.",
      "Ranged physical damage +25%.",
      "P.ATK +8.",
      "^0055AAGrade D or higher:^000000",
      "ATK +5%.",
      "POW +5.",
      "^0055AAGrade C or higher:^000000",
      "P.ATK +7.",
      "ATK +25.",
      "^0055AAGrade B or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "Variable cast time -10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against non-player races +4% per 3 refine",
      "levels.",
      "_______________________",
      "^0055AASet: with Fighter's Cloak (ID 480671)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Non-critical physical damage +15%.",
      "P.ATK +5.",
      "^0055AAcrown Grade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Champion's Cloak (ID 480672)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Melee physical damage +10%.",
      "Ranged physical damage +10%.",
      "P.ATK +4.",
      "Max HP +3%.",
      "^0055AAcrown Grade A:^000000",
      "Physical damage against all target elements +10%.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 65",
      "Required Level: 250",
      "Card Slots: 1",
      "Weight: 40",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: All jobs (subject to required level)",
    },
    slotCount = 1, ClassNum = 2393, costume = false
  },
  [401057] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Violet Stardust Crown",
    identifiedResourceName = "Poenetentia_S_Crown",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "SPL +5.",
      "CON +5.",
      "MATK +25 per 2 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Variable cast time -10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +7.",
      "MATK +12%.",
      "^0055AARefine +11 or higher:^000000",
      "All-element magic damage +25%.",
      "S.MATK +8.",
      "^0055AAGrade D or higher:^000000",
      "MATK +5%.",
      "SPL +5.",
      "^0055AAGrade C or higher:^000000",
      "S.MATK +7.",
      "MATK +25.",
      "^0055AAGrade B or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "After-cast delay -7%.",
      "^0055AAGrade A:^000000",
      "Magic damage against non-player races +4% per 3 refine levels.",
      "_______________________",
      "^0055AASet: with Scholar's Muffler (ID 480673)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Neutral-element magic damage +15%.",
      "Fire-element magic damage +15%.",
      "Earth-element magic damage +15%.",
      "Water-element magic damage +15%.",
      "Wind-element magic damage +15%.",
      "Poison-element magic damage +15%.",
      "Dark-element magic damage +15%.",
      "S.MATK +5.",
      "^0055AAcrown Grade A:^000000",
      "Magic damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Wizard's Cloak (ID 480674)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Undead-element magic damage +15%.",
      "Fire-element magic damage +15%.",
      "Neutral-element magic damage +15%.",
      "Wind-element magic damage +15%.",
      "Ghost-element magic damage +15%.",
      "Holy-element magic damage +15%.",
      "Dark-element magic damage +15%.",
      "S.MATK +5.",
      "^0055AAcrown Grade A:^000000",
      "Magic damage against all target elements +10%.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 35",
      "Required Level: 250",
      "Card Slots: 1",
      "Weight: 40",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: All jobs (subject to required level)",
    },
    slotCount = 1, ClassNum = 2506, costume = false
  },
  [401058] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Celestial Rune Crown (Imperial Guard)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "Holy-element magic damage +2% per 3 refine levels.",
      "Neutral-element magic damage +2% per 3 refine levels.",
      "MATK +2% per 3 refine levels.",
      "Imperial Pressure damage +5% per 4 refine levels.",
      "Cross Rain damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Holy-element magic damage +10%.",
      "Neutral-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade C or higher:^000000",
      "After-cast delay -10%.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Imperial Spear of the Sky (ID 530076)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Holy-element magic damage +15%.",
      "Neutral-element magic damage +15%.",
      "Cross Rain damage +35%.",
      "^0055AAcrown Grade A; right-hand weapon Grade A:^000000",
      "Cross Rain damage +20%.",
      "Cross Rain cooldown -1 sec.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Imperial Guard (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401059] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Celestial Rune Crown (Abyss Chaser)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "HIT +5 per 2 refine levels.",
      "Non-critical physical damage +3% per 3 refine levels.",
      "Melee physical damage +1% per 3 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Chasing Break damage +5% per 4 refine levels.",
      "Deft Stab damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "After-cast delay -10%.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Deft Stab damage +15%.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Chasing Dagger of the Sky (ID 510199)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Non-critical physical damage +15%.",
      "Deft Stab damage +45%.",
      "^0055AAcrown Grade A; Deft Stab learned at Lv. 10 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Chasing Break cooldown -0.3 sec.",
      "Using Chasing Break: 100% trigger chance to autocast Lv. 10 Deft",
      "Stab.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Abyss Chaser (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401060] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Rune Crown of the Sky (Spiritualist)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "CRIT +2 per 2 refine levels.",
      "ATK +3 per 2 refine levels.",
      "Critical-damage bonus +3% per 3 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Hogogong Strike damage +7% per 4 refine levels.",
      "Chulho Battering damage +7% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Ranged physical damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Hogogong Strike damage +15%.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Foxtail of the Sky (ID 550187)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Critical-damage bonus +15%.",
      "Chulho Sonic Claw damage +40%.",
      "^0055AAcrown Grade A; Hogogong Strike learned at Lv. 7 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Chulho Battering cooldown -0.25 sec.",
      "Using Chulho Battering: 100% trigger chance to autocast Lv. 7",
      "Hogogong Strike.",
      "Critical-damage bonuses apply at half their rate to critical",
      "skills in Renewal.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Summoner family; no class-tier filter",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401115] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Meister)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "HIT +5 per 2 refine levels.",
      "Non-critical physical damage +3% per 3 refine levels.",
      "Melee physical damage +1% per 3 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Rush Strike damage +5% per 4 refine levels.",
      "Powerful Swing damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "After-cast delay -10%.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Powerful Swing damage +15%.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Sky Rush Axe (ID 28145)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Non-critical physical damage +15%.",
      "Powerful Swing damage +35%.",
      "^0055AAcrown Grade A; Powerful Swing learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Using Rush Strike: 100% trigger chance to autocast Lv. 5",
      "Powerful Swing.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Meister (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401116] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Windhawk)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "CRIT +2 per 2 refine levels.",
      "ATK +3 per 2 refine levels.",
      "Critical-damage bonus +3% per 3 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Crescive Bolt damage +5% per 4 refine levels.",
      "Hawk Rush damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Ranged physical damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Hawk Rush damage +15%.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Celestial Crescent Bow (ID 700125)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Critical-damage bonus +15%.",
      "Hawk Rush damage +40%.",
      "^0055AAcrown Grade A; Hawk Rush learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Using Crescive Bolt: 100% trigger chance to autocast Lv. 5 Hawk",
      "Rush.",
      "Critical-damage bonuses apply at half their rate to critical",
      "skills in Renewal.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Windhawk (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401117] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Hyper Novice)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "Ghost-element magic damage +2% per 3 refine levels.",
      "Wind-element magic damage +2% per 3 refine levels.",
      "MATK +2% per 3 refine levels.",
      "Napalm Vulcan Strike damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Ghost-element magic damage +10%.",
      "Wind-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Napalm Vulcan Strike damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Celestial Napalm Sword (ID 500134)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Napalm Vulcan Strike damage +35%.",
      "^0055AAcrown Grade A; combined crown/right-hand weapon refine at least^000000",
      "^0055AA24; right-hand weapon Grade A:^000000",
      "Chain Lightning damage +2% per combined crown/right-hand weapon",
      "refine level.",
      "^0055AAcrown Grade A; Chain Lightning learned at Lv. 5 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Using Napalm Vulcan Strike: 100% trigger chance to autocast Lv.",
      "5 Chain Lightning.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Hyper Novice (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401118] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Cardinal)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "MATK +5 per 2 refine levels.",
      "Holy-element magic damage +2% per 3 refine levels.",
      "MATK +2% per 3 refine levels.",
      "Arbitrium damage +5% per 4 refine levels.",
      "Framen damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Holy-element magic damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "S.MATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Fixed cast time -0.5 sec.",
      "^0055AAGrade D or higher:^000000",
      "S.MATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Framen damage +10%.",
      "^0055AAGrade B or higher:^000000",
      "Magic damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Magic damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Celestial Arby Rod (ID 550190)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Holy-element magic damage +15%.",
      "Framen damage +35%.",
      "^0055AAcrown Grade A; Framen learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Using Arbitrium: 100% trigger chance to autocast Lv. 5 Framen.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Cardinal (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401119] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Inquisitor)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "HIT +5 per 2 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Max HP +3% per 3 refine levels.",
      "Third Flame Bomb damage +5% per 4 refine levels.",
      "Tiger Cannon damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "Perfect-hit chance +5 percentage points.",
      "Max HP +5%.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Tiger Cannon damage +15%.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Celestial Annihilation (ID 560086)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Melee physical damage +15%.",
      "Tiger Cannon damage +40%.",
      "^0055AAcrown Grade A; Tiger Cannon learned at Lv. 10 or higher;^000000",
      "^0055AAcombined crown/right-hand weapon refine at least 24; right-hand^000000",
      "^0055AAweapon Grade A:^000000",
      "Using Third Flame Bomb: 100% trigger chance to autocast Lv. 10",
      "Tiger Cannon.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Inquisitor (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
  [401120] = {
    unidentifiedDisplayName = "Unidentified Headgear",
    unidentifiedResourceName = "EpisodClear20",
    unidentifiedDescriptionName = { "Identify this headgear to view its name." },
    identifiedDisplayName = "Sky Rune Crown (Sky Emperor)",
    identifiedResourceName = "Midgard_Diadem_JP",
    identifiedDescriptionName = {
      "Effects follow this server. Refine steps round down.",
      "All met refine/grade conditions stack.",
      "^0055AAUnconditional bonuses:^000000",
      "ATK +3 per 2 refine levels.",
      "HIT +5 per 2 refine levels.",
      "Non-critical physical damage +3% per 3 refine levels.",
      "Melee physical damage +1% per 3 refine levels.",
      "ATK +2% per 3 refine levels.",
      "Sky Moon damage +5% per 4 refine levels.",
      "Star Light Kick damage +5% per 4 refine levels.",
      "^0055AARefine +7 or higher:^000000",
      "Melee physical damage +10%.",
      "^0055AARefine +9 or higher:^000000",
      "P.ATK +5.",
      "^0055AARefine +11 or higher:^000000",
      "SP consumption -5%.",
      "^0055AAGrade D or higher:^000000",
      "P.ATK +5.",
      "^0055AAGrade C or higher:^000000",
      "Sky Moon damage +15%.",
      "^0055AAGrade B or higher:^000000",
      "Physical damage against all sizes +10%.",
      "^0055AAGrade A:^000000",
      "Physical damage against all target elements +10%.",
      "_______________________",
      "^0055AASet: with Celestial Moonsong Book (ID 540122)^000000",
      "^0055AAUnconditional bonuses:^000000",
      "Non-critical physical damage +15%.",
      "Sky Moon damage +45%.",
      "^0055AAcrown Grade A; Sky Moon learned at Lv. 5 or higher; combined^000000",
      "^0055AAcrown/right-hand weapon refine at least 24; right-hand weapon^000000",
      "^0055AAGrade A:^000000",
      "Star Light Kick cooldown -0.25 sec.",
      "Using Star Light Kick: 100% trigger chance to autocast Lv. 5 Sky",
      "Moon.",
      "Non-critical bonus excludes skills flagged to ignore it.",
      "Autocasts remain subject to server skill, target and equipment",
      "restrictions.",
      "_______________________",
      "Type: Upper Headgear",
      "Armor Level: 2",
      "DEF: 50",
      "Required Level: 240",
      "Card Slots: 1",
      "Weight: 0",
      "Refineable: Yes",
      "Gradable: Yes",
      "Equip: Sky Emperor (fourth class)",
    },
    slotCount = 1, ClassNum = 2692, costume = false
  },
}
